export const SAVE_USER = 'SAVE_USER'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const LOG_OUT = 'LOG_OUT'
export const GET_USER_DATA = 'GET_USER_DATA'
export const GET_FOLLOWERS = 'GET_FOLLOWERS'
export const GET_FOLLOWING = 'GET_FOLLOWING'
export const GET_USER_GROW_LIST = 'GET_USER_GROW_LIST'
