export const GET_FAVORITE_CROPS_TO_GROW = 'GET_FAVORITE_CROPS_TO_GROW';
export const GET_CROP_VARIETIES = 'GET_CROP_VARIETIES';
export const GET_CROP_CYCLE_DETAILS = 'GET_CROP_CYCLE_DETAILS';
export const GET_CROP_STEPS = 'GET_CROP_STEPS'