export const GET_USER_JOBS = 'GET_USER_JOBS';
export const LOADING_JOBS = 'LOADING_JOBS'
export const GET_CURRENT_GROW_CROPS = 'GET_CURRENT_GROW_CROPS'
export const GET_PASSED_HARVEST = 'GET_PASSED_HARVEST'